# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support documentation.
# This workflow will download a prebuilt Python version, install dependencies, build and deploy/publish a new release
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Deploy and Publish

on:
  pull_request:
  # Sequence of patterns matched against refs/heads
    branches:
      - master
  push:
    branches:
       - master
#  workflow_run:
#    workflows: ["Build and Test"]
#    branches: [ master ]
#    types:
#      - completed
#  # Allows you to run this workflow manually from the Actions tab
#  workflow_dispatch:


jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.7'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Test with pytest
        run: |
          pytest
  deploy:
    #if: github.event.pull_request.merged == true
    name: Deploy and Publish
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        persist-credentials: false
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.7'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Test with pytest
      run: |
        pytest
      - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: 16
    - name: Install Semantic Release dependencies
      run: |
        sudo apt-get install bumpversion
        npm install -g semantic-release
        npm install -g @semantic-release/changelog
        npm install -g @semantic-release/exec
        npm install -g @semantic-release/git
        npm install -g @semantic-release/github
        npm install -g @semantic-release/commit-analyzer
        npm install -g @semantic-release/release-notes-generator
    - name: Publish to Git Releases and Tags
      run: npx semantic-release #--dry-run --branches 9388_gha Uncomment for testxing purposes
      env:
        GITHUB_TOKEN: ${{ secrets.c }}
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    - name: Build binary wheel and a source tarball
      run: |
        pip3 install setuptools wheel twine build
        python -m build --sdist --outdir dist/
    - name: Publish distribution to PyPI
      uses: pypa/gh-action-pypi-publish@v1.4.2 # Try to update version tag every release
      with:
        password: ${{ secrets.PYPI_TOKEN }}
        repository_url: https://upload.pypi.org/legacy/ # This must be changed if testing deploys to test.pypi.org
